#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh &



nitrogen --restore &
xfce4-power-manager &
picom &
dunst &

bspc monitor -d  I II III IV V VI

bspc config border_width         5
bspc config window_gap          13

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#### BSPWM coloring ####
bspc config normal_border_color		      "#4C566A"
bspc config active_border_color	              "#8700ff"
bspc config focused_border_color	      "#8700ff"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"
k

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 
brightnessctl set 0  
sudo pacman -Rns $(pacman -Qtdq) --noconfirm
